image: 4lt4/gif2spr-build

stages:
    - build

build-linux:
    stage: build
    before_script:
        - apt-get update && apt-get -y install libgif-dev 
    script:
        - make

build-windows:
    stage: build
    script:
        - make TARGET_PLAT=win32 win-gui
    artifacts:
        paths:
            - gif2spr.exe
            - gif2spr-gui.exe
            - LICENSE.txt
            - LICENSE_3rd_party
            - README.md

# run tests using the binary built before
# test:
#   stage: test
#   script:
#     - ./runmytests.sh
