image: gcc

stages:
    - stats
    - build
    
stats:
    stage: stats
    script:
    - uname -a

build-linux:
    stage: build
    # instead of calling g++ directly you can also use some build toolkit like make
    # install the necessary build tools when needed
    before_script:
        - apt-get update && apt-get -y install libgif-dev 
    script:
        - make

build-windows:
    stage: build
    before_script:
        - apt-get update && apt-get -y install mingw-w64 wget
    script:
        - mkdir buildbin
        - wget -o buildbin/tclkit http://tclkits.rkeene.org/fossil/raw/tclkit-8.6.3-rhel5-x86_64?name=36b5cb68899cfcb79417a29f9c6d8176ebae0d24
        - wget -o buildbin/sdx.kit https://chiselapp.com/user/aspect/repository/sdx/uv/sdx-20110317.kit
        - chmod +x buildbin/tclkit buildbin/sdx.kit
        - export PATH=`pwd`/buildbin:$PATH
        - make TARGET_PLAT=win32 win-gui
    artifacts:
        paths:
            - gif2spr.exe
            - gif2spr-gui.exe
            - COPYING
            - README.md

# run tests using the binary built before
# test:
#   stage: test
#   script:
#     - ./runmytests.sh
